### ISSUE TITLE
Warning when internet connection is gone/poor

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#111]

**Comment by Nuytemans-Dieter** [comment]
Perhaps a [http request](https://api.dartlang.org/stable/2.5.2/dart-io/HttpClient-class.html) could prove useful

**Comment by TNelen** [comment]
checking internet connectivity on app startup when logging in. also implemented a popup indicating when wifi/4g is turned off. 

Is it still necessary to check this again during game?
Suggestion: Postpone issue to later release, this is not really necessary at the moment.

**Comment by Nuytemans-Dieter** [comment]
Perhaps not necessary but it would be a nice addition. Further down the line, we could perhaps add a runnable that runs each x seconds and check the connectivity.

**Comment by TNelen** [comment]
> Perhaps not necessary but it would be a nice addition. Further down the line, we could perhaps add a runnable that runs each x seconds and check the connectivity.

Removing this issue from Release 1.0.5, + giving suggestion label

**Comment by TNelen** [comment]
after further consideration this issue is closed
