### ISSUE TITLE
Top 3 is not always correct

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [TNelen/BlackBox#122]

**Comment by TNelen** [comment]
Winner is shown correctly. 

But sometimes 2 and 3 are switched

**Comment by TNelen** [comment]
Winner is shown correctly. 

But sometimes 2 and 3 are switched

**Comment by Nuytemans-Dieter** [comment]
This is likely fixed in 9030fb2091e40730f648196f6f9331e1677bfe91 by rewriting the top three calculation
