### ISSUE TITLE
Giving feedback to questions does not always works correctly

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#123]
Sometimes with new question the feedback you have given to a previeous question remains.

Add option to uncheck things. (IMPORTANT: add change limiter to reduce database writes)

**Comment by Nuytemans-Dieter** [comment]
Random thought: What if we only submit the feedback to the database when moving to the next screen? No more than one write would be used @TNelen

**Comment by TNelen** [comment]
@Nuytemans-Dieter  Good idea!

**Comment by TNelen** [comment]
added a toggle function, selected elements can now be unchecked
