### ISSUE TITLE
show timer (time left to vote) to other players (not only admins)

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#125]
Iets met boolean in database to start timer

Suggestion: show clean popup bubble with time left warning

**Comment by TNelen** [comment]
When admin votes, a bool in groupdata in database is set to true, other players detect this and a countdown popup is shown

**Comment by TNelen** [comment]
@Nuytemans-Dieter, provide bool support in database
I handle the popup.

**Comment by Nuytemans-Dieter** [comment]
A field with a timestamp will be implemented in GroupData and the database. This will indicate the moment the countdown started.

**Comment by TNelen** [comment]
Maybe use dismissable?
https://www.youtube.com/watch?v=iEMgjrfuc58
