### ISSUE TITLE
Sometimes a vote is lost

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#127]
Sometimes a vote is lost. 

Vermoeden: dit gebeurt als er een device crashed. Maar niet zeker of dit altijd zo is

**Comment by Nuytemans-Dieter** [comment]
Might have been fixed by a936ac032b21adb1eb9df7b09a178066374bcc5c but I have been unable to confirm this (the exact cause of the crash is still unknown)

**Comment by Nuytemans-Dieter** [comment]
In the GroupData vote method, a retry after a random time should be added

**Comment by Nuytemans-Dieter** [comment]
A random retry has been implemented in `GroupData#addVote()` and it has been confirmed to still be functional. However, further testing is required to check if this issue is resolved. Moving to `Further Testing`

**Comment by TNelen** [comment]
Issue did not arrise in further versions. Issue can be closed
