### ISSUE TITLE
bij crash van iemand wordt soms top 3 niet correct getoond bij de rest, of leidt dit tot het overslagen van een vraag

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#132]

**Comment by Nuytemans-Dieter** [comment]
Might have been fixed by a936ac032b21adb1eb9df7b09a178066374bcc5c but I have been unable to confirm this (the exact cause of the crash is still unknown)

**Comment by Nuytemans-Dieter** [comment]
Moving to [Further testing](https://github.com/TNelen/BlackBox/milestone/7)
