### ISSUE TITLE
Layout result redesing

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#133]
other centering

**Comment by TNelen** [comment]
Suggestion: Maybe do a full design overhaul, and change it from cards to a more vertical format?
@Nuytemans-Dieter , what do you think, or do you like the card design more?

**Comment by TNelen** [comment]
Working on it, moving it to release 1.0.4

**Comment by Nuytemans-Dieter** [comment]
> Suggestion: Maybe do a full design overhaul, and change it from cards to a more vertical format?
> @Nuytemans-Dieter , what do you think, or do you like the card design more?

I'm just seeing this now. A vertical format is more user friendly in my opinion.

**Comment by TNelen** [comment]
Entirely new design :) I'm very proud of it :)
Closing this issue with pleasure;
