### ISSUE TITLE
category with only own questions

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#134]

**Comment by TNelen** [comment]
This needs further brainstorming..;
What to do when there are no questions? Give users time to submit questions? Or collect all questions in the beginning of the game. Or let all users ask a question one by one.

**Comment by Nuytemans-Dieter** [comment]
We could make these private/local questions which will not be saved in the community questions and will be deleted when the group is deleted. This allows for questions that only that group would understand, like inside jokes or certain events that those users shared. @TNelen Is that the intention? I believe that would be the best approach for this situation.

In my head, I see several options or perhaps a combination of the following (and including @TNelen 's ideas for a better overview):
- From a user perspective 
   - This happens before playing until everyone has readied up or the time runs out.
   - After each round, a different user may write a question for the group
   - We can grab all questions that a user has submitted to the community questions in the past. 
       - Or as combination: a button to select my previous questions which will open a screen with all earlier submitted questions. The user can check all/uncheck all or do this individually and then submit all those questions at once.
- From a dev perspective
    - Either a temporary category is made in `questions` and the game works as usual, using all question IDs from this category. These user submitted questions and the category should be deleted which may be a dangerous operation.
    - The questions are stored in the group itself, this will provide easier deletion but a new system must be created to read these questions, this is more work but the questions are automatically deleted when the group is deleted.
