### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#148]

**Comment by TNelen** [comment]
Push notifications:
* for users when they have not used the app in a long time
* When update is available
* Other...

**Comment by Nuytemans-Dieter** [comment]
I am really fond of this idea. This might be a nice addition for the 1.0.5 milestone?

**Comment by TNelen** [comment]
Implemented in Beta 3.0.8 and further.
Functionality is tested in beta
