### ISSUE TITLE
App usage insights

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#157]
Look if there is a plugin for usage statistics

**Comment by TNelen** [comment]
name screens
EX: see how many users went to settings screen/profile screen etc

**Comment by TNelen** [comment]
check this link
https://medium.com/flutterdevs/firebase-analytics-2044e865efc4

**Comment by Nuytemans-Dieter** [comment]
The command that failed is only useful for debugging (analytics -> debug view in the firebase console). Make sure that command is in your path variables so it can be ran from everywhere the app name is `be.dezijwegel.blackbox´.
For the real deal, you can simply follow that article to report custom events. I am not sure in which spots it would be interesting to put usage data collection and which parameters to pass (time spent, page name, ..)

**Comment by Nuytemans-Dieter** [comment]
Implemented in: 5f84a6337eef0bd52620bd9ed539acfa9cbc7d8b, 7fb0a3081339d993310d1ae2f0febda2673dfd47, 1ce052dd424084f316435d8c1d1baa26dc20c34d, 761177f19b5f423f5c54ecb4cacd5a747ec407f5 and 6c869da668bb9a7510b642fe5f9d62095adf2687
