### ISSUE TITLE
remove group after inactivity

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#168]

**Comment by TNelen** [comment]
Maybe do this with cloud functions

**Comment by TNelen** [comment]
fix admin vote timestamp
* is now set to null after ready of group

use this timestamp to determine is group activity was more than week ago

**Comment by Nuytemans-Dieter** [comment]
Scheduled functions are only available with the blaze plan.. perhaps manually call this function every now and then?

**Comment by Nuytemans-Dieter** [comment]
I implemented a timestamp to trace the last group update in 740c9432c32f19bc067964d53d3486451e354be2. If needed, I can create a function that takes care of old groups. Any period of time can be used to filter on this.

Note that the timestamp is probably in local time, so it can vary (but no more than a 27 hour difference).

**Comment by Nuytemans-Dieter** [comment]
Implemented a method for removing old groups in d42b7aaf1f1d2fbef97203bfd9af11f8e8ec97f3. It has to be called manually but will allow removal of inactive groups.
Groups before this update shouldn't be affected, a similar method could be used to clean the database.
