### ISSUE TITLE
ability to select multiple categories

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#173]
**UI**
desciption
amount of questions in category

**Comment by TNelen** [comment]
seelction can be done

need to put list in groupdata object

get question id's from multiple lists
+ NOTE: item 0 is group description so do not include that in the list!

**Comment by TNelen** [comment]
Add pagination of the categories

**Comment by Nuytemans-Dieter** [comment]
> seelction can be done
> 
> need to put list in groupdata object
> 
> get question id's from multiple lists
> 
> * NOTE: item 0 is group description so do not include that in the list!

Done, and added shuffling in 03e590f7ecb92a173ae4db8bc499de356a5bb4ab
