### ISSUE TITLE
disable ability to rotate screen, or optimize screen rotation

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#176]

**Comment by Nuytemans-Dieter** [comment]
Disabling rotation seems like less work, and I personally don't see the need to allow screen rotation.

**Comment by Nuytemans-Dieter** [comment]
Should be implemented in 11db625a2bf7f79a151c3f3d8159270161d1dab1. And is working for me, please double check @TNelen

**Comment by TNelen** [comment]
works like a charm :) GJ @Nuytemans-Dieter
