### ISSUE TITLE
ready button not behaving optimal

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#177]
sometimes 2 presses needed for it to react

**Comment by TNelen** [comment]
This is due to latency on the firebase interaction i think, because screen is reloaded when new info is received in datastream; so field in database needs to be adjusted before button is changed.

not much we can change about it imo. Or we need to change mechanic, keep local bool whether button is pressed, but adds new complexity when stating game and field in database is not set properly etc.

afaik this is best approach, but is has it's limitations

@Nuytemans-Dieter  what's your take on this? Maybe you think the delay is due to other issue?

**Comment by Nuytemans-Dieter** [comment]
Agreed on the cause. A local boolean would be a better UX initially but the next screen would be a problem (annoying forced waiting screen probably). So I agree that the current state is sufficient and we may look back some time in the future.

**Comment by Nuytemans-Dieter** [comment]
Did some testing and ran into this issue again randomly. Testing with physical device and emulator.
Both users were ready but the 'start game' text did not show up. Even after unready-ing  either one of them, start game did not pop up after pressing ready again.

I got it working by unready-ing everyone and then pressing on ready again. Perhaps this might give some more insight one day.

**Comment by TNelen** [comment]
issue could be solved in 8b7aa926ba628c98d49b069544b5522e22cce8f0

Due to no other clues, I'm closing this issue for now.

**Comment by TNelen** [comment]
Button was still behaving strange: this could be solved in c7f6943d2227f000f44ce4d8acee1641e00f6c42

**Comment by TNelen** [comment]
Strange behaviour is due to network latency; Maybe we could add redundant check to database to see for amount of players ready?

**Comment by Nuytemans-Dieter** [comment]
> Strange behaviour is due to network latency; Maybe we could add redundant check to database to see for amount of players ready?

That could work, I'm not exactly sure how to improve this otherwise..

**Comment by TNelen** [comment]
What kind of check would you recommend?

Imo sth like a poll each x seconds. But to reduce dB reads only when already 75% of players are ready? 

Or maybe we can skip the 'all players need to be ready requirement altogether' or come up with a hybrid solution? 

@Nuytemans-Dieter your thoughts?

**Comment by Nuytemans-Dieter** [comment]
@TNelen 
There are a few things we can try imo but there is no certain fix. We'll have to try and see what works.
- Indeed a (read intensive) poll, as long as all but a few players are ready (eg. 5 players and 3 are ready -> start polling)
- Add a field indicating whether the game can start? Any player can set this to true if everyone is ready for them. It can be set to false whenever someone joins the group.
- Perhaps (if the groupdata is correct, won't help otherwise), perform a setState periodically to trigger rebuilds. I don't think the issue lies there though.

**Comment by TNelen** [comment]
Field in database is set correctly to playing... So perhaps groupdata issue lays indeedwith the _setstate_ not called when receiving new groupdata?

**Comment by TNelen** [comment]
@Nuytemans-Dieter  i did some testing and it seems like the groupdata local aswell as in database is correct, but maybe due to render timing the button is not changed correctly.

Can you confirm this also with some testing; printing the received groupdata isPlaying list and checking this with database should be sufficient; I recommend doing this on physical device since issue occurs more there;

**Comment by TNelen** [comment]
I cannot reproduce the ready button issue when using group with 2 users. One emulator and one physical device; I think an extra render or sth like that should do the job since local groupdata is correct.

**Comment by Nuytemans-Dieter** [comment]
If needed I can do more testing tonight, otherwise we could perhapsjust try a periodic refresh?

**Comment by TNelen** [comment]
This could be related
https://flutterforum.co/t/streambuilder-sometimes-not-refreshing-my-listview/1251

**Comment by Nuytemans-Dieter** [comment]
What about adding something like this in GameScreen?
Haven't tested this in IDE (wrote this in browser) so not sure if all the syntax checks out.
```
  Timer _rebuildTimer;

  @override
  void initState() {
    _rebuildTimer = new Timer.periodic(
        Duration(seconds: 1), 
        () => setState({})
    );
    super.initState();
  }

  @override
  void dispose() {
    _rebuildTimer.cancel();
    super.dispose();
  }
```

**Comment by TNelen** [comment]
Still issues with the button. It might be because the groupdata is written to database twice. It is automatically written to the database when picking nexwtQuestion and afterwards manually in when pressing the ready button. 
![image](https://user-images.githubusercontent.com/37212860/92274743-1038b380-eeee-11ea-92e9-8a8f2badff90.png)

But this is only done when player is admin.

**Comment by TNelen** [comment]
i tried moving the setNextQuesdtion to the beginning when user joings group, but same issue here because we write twice fast after each other.

![image](https://user-images.githubusercontent.com/37212860/92275195-f9df2780-eeee-11ea-8d35-2a56ffedc30a.png)

**Comment by TNelen** [comment]
@Nuytemans-Dieter can you try setting the NextQuestion on group creation?

**Comment by Nuytemans-Dieter** [comment]
> @Nuytemans-Dieter can you try setting the NextQuestion on group creation? 

Will see what I can do and I'll get back at you soon.

**Comment by Nuytemans-Dieter** [comment]
@TNelen Done :)

**Comment by TNelen** [comment]
Testing confirms that the ready button is working perfectly now since a99abc6a74e5653b2f8c0c953f94f0f22ba5f209

Let's close this issue forever now (hopefully)
