### ISSUE TITLE
refactoring question class

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#178]
categories are updated so refactor this class
delete unused methods etc

**Comment by Nuytemans-Dieter** [comment]
Removed the Category enum throughout the full codebase in 4c72cd94701a14d535f79c5a0b3144d244ae8cc9.
Adding questions in the new system is a lot easier: see commit 53b5f3e827a2dee41d121935c52d264dc379520b.

No checks have been done regarding unused methods but afaik, everything should still be functional.

**Comment by Nuytemans-Dieter** [comment]
Implemented a method for removing old groups in d42b7aaf1f1d2fbef97203bfd9af11f8e8ec97f3. It has to be called manually but will allow removal of inactive groups.
Groups before this update shouldn't be affected, a similar method could be used to clean the database.

**Comment by TNelen** [comment]
Looks good! some more improvement can be made in deleting unused methods
I'm not sure to which extend there are still unused methods. I'm opening new issue for that
