### ISSUE TITLE
submit question not working whne playing with multiple users

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#187]
new question not added to question list

? does this issue only occurs when playing with multiple users?

**Comment by Nuytemans-Dieter** [comment]
Still not sure about this one.

**Comment by Nuytemans-Dieter** [comment]
This has been fixed but must be tested as well. Perhaps other mechanics break now?

**Comment by Nuytemans-Dieter** [comment]
This issue seems to be fixed. Closing for now.
