### ISSUE TITLE
Enable/disable popup(s) in database

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [TNelen/BlackBox#190]
Add a variable to the AppInfo document in the database that states whether or not to display a popup.
This way, we can remotely enable or disable the update popup when something goes wrong.

In addition, this change will not result in any extra reads as that document is read whenever an app opens anyway.

**Comment by TNelen** [comment]
Good idea!

**Comment by TNelen** [comment]
Maybe do the same as with the message? When empty, do not display pop-up?

**Comment by Nuytemans-Dieter** [comment]
> Maybe do the same as with the message? When empty, do not display pop-up?

Great idea!
