### ISSUE TITLE
Support more different sizes of devices

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [TNelen/BlackBox#191]
For example the HomeScreen:
![image](https://user-images.githubusercontent.com/37397560/90257708-cd804000-de47-11ea-8aa3-7390ca868535.png)

**Comment by Nuytemans-Dieter** [comment]
Forgot to mention this issue in 8878a288fa003f6fbea3d20c3032d281b9869a64

**Comment by TNelen** [comment]
First improvements made in ee4edf00723645fd4159716313f4c3f7369872cb

**Comment by TNelen** [comment]
More improvements can be made in #192 , closing this issue now:
