### ISSUE TITLE
Join group TextInputField is hidden by keyboard on some devices

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [TNelen/BlackBox#194]
> Mijn pa zijn toetsenbord is nogal lang en dus terwijl hij de joincode probeert in te geven ziet hij deze niet omdat die achter het toetsenbord is verdwenen. Hij kan wel typen. Doordat het ook niet zichtbaar is kan hij niet plakken.

![image](https://user-images.githubusercontent.com/37397560/90284534-6a57d300-de72-11ea-9cea-b29a4e74ecf4.png)

**Comment by TNelen** [comment]
closed in 8878a288fa003f6fbea3d20c3032d281b9869a64
