### ISSUE TITLE
Implement CI/CD for this repo

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [TNelen/BlackBox#198]
See [this article](https://medium.com/@iqan/ci-cd-for-flutter-android-app-using-github-actions-ea065180a3be).

**Comment by Nuytemans-Dieter** [comment]
First test of this at 2f6ed3d2697421ff59fa092cb6837469458b0b03

**Comment by Nuytemans-Dieter** [comment]
Build status is being checked for each push/PR to master.
@TNelen Is that good enough for now or do you suggest more advanced actions?

**Comment by TNelen** [comment]
@Nuytemans-Dieter  good for now; We'll see what other advancements we can make in future; I'm thinking about automatic release to google play when pushed to master etc. But refactoring of branches is needed for that - release branches & feature branches on release branch.
But for now this is good start;
