### ISSUE TITLE
choose accent color when changing splash color is not correct

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#205]
The splash color of the card is still the old accent color. Idk if this is easy fix @Nuytemans-Dieter?

**Comment by Nuytemans-Dieter** [comment]
@TNelen 
Which widget or page is this referring to? ToggleButtonCard?
The splashcolor of that InkWell is currently `Constants.colors[Constants.colorindex]`, should this be something else?

**Comment by TNelen** [comment]
Yes, in the setting screen when changing accent color, the splash animation on the card should be the color what the card represents, so the future accent color. Ex when your accent color is green, you change it to blue, then animation on the green card is still green, but is should already be blue.

**Comment by Nuytemans-Dieter** [comment]
Ah, I get it now. Should not be too hard to fix.
