### ISSUE TITLE
New Update availible popup

### ISSUE THREAD

**Issue by WannesMaes** [TNelen/BlackBox#212]
The popup keeps apearing even though i have te latest version.

**Comment by TNelen** [comment]
This is because you have beta version

Fix: create a sperate version in database for beta release.

**Comment by TNelen** [comment]
@Nuytemans-Dieter fix extra field in database

**Comment by Nuytemans-Dieter** [comment]
@TNelen 
What about jusg comparing the build numbers instead? And only show the popup when the current version is smaller than the build number in database?

**Comment by TNelen** [comment]
> @TNelen
> What about jusg comparing the build numbers instead? And only show the popup when the current version is smaller than the build number in database?

Good idea, that's even better. In that way we can for example only show popup to users 2 versions later than latest release etc

**Comment by Nuytemans-Dieter** [comment]
> Good idea, that's even better. In that way we can for example only show popup to users 2 versions older than latest release etc
With the latest commit (see above), it just checks if the version is smaller. Should this be changed to two versions?

**Comment by TNelen** [comment]
1 version is good for now 🙂 issue can be closed
