### ISSUE TITLE
Crash app when submitting an expired joincode

### ISSUE THREAD

**Issue by WannesMaes** [TNelen/BlackBox#213]
**Description**
Made a game and copied the joincode. Started the game (1 player), played for a question, then left the game in a correct way.
Tried to join the game (that doesn't exist anymore) and came on a black screen. After that i couldn't go back (no button on screen or with the android back button). Only choice close the app and start again.
Afterwards i tried again, came on the same black screen, but the android back button works this time.

**Possible improvement**
- Check the correctness of the joincode, if not correct, then don't go to the next (black)screen and display an error message. 
-  If not in a game: catch all unhandled errors and go to the homescreen and display an error message.
-  If in a game: catch all unhandled errors and go to the joinscreen, prefill the joincode with last game joincode and display an error message.

**Comment by TNelen** [comment]
Normally there should be a popup 'This group does not exist but it seems like this error is not caught and the popup is not thrown correctly here.
This worked in previous releases.

**Comment by TNelen** [comment]
FYI, the app does not crash here, but waits for a database response with the data about the group, but since the group does not exist, no valid response is coming and it keeps waiting indefinitely.

**Comment by TNelen** [comment]
@Nuytemans-Dieter  is it possible to make new firebase method `checkGroupExist(String groupcode)` ? 
There currently is no check in place to see if the groupcode is existing

**Comment by TNelen** [comment]
First step made in 39b6a45c7b283b14580e48b03a2944cded1f4225
