### ISSUE TITLE
include players with 0 votes in leaderboard

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#214]

**Comment by TNelen** [comment]
i think this is ez fix, when we put all players in the newvotes with zero votes. because now resultscreen is based upon the map in the newvotes. Players with zero votes just are not in the map. If we include these they should be displayed in the result screen automatically.

this is just suggestion, what are your thoughts @Nuytemans-Dieter ?

**Comment by Nuytemans-Dieter** [comment]
> i think this is ez fix, when we put all players in the newvotes with zero votes. because now resultscreen is based upon the map in the newvotes. Players with zero votes just are not in the map. If we include these they should be displayed in the result screen automatically.
> 
> this is just suggestion, what are your thoughts @Nuytemans-Dieter ?

I'm not sure how this works by heart. Will take a look soon and fix :)

**Comment by Nuytemans-Dieter** [comment]
newVotes only maps actual votes, the only list with an actual amount of votes is the total vote count. Found a way around this by editing some functions in groupdata.
