### ISSUE TITLE
Make 'rate this app' smarter

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [TNelen/BlackBox#217]
There is no way to tell whether a user has left a review for the app. Let alone the number of stars they gave it.
What if we only allow them to rate the app (in-app popup) once and then assume that score forever?
The reason for this is that it feels cheap if they for example rate 2 stars, get a contact popup and then rate more stars because they (quite likely imo) think that that will bring them to the store and they'll probably leave an extra bad review. The drawback is that they cannot change their mind.

**Comment by TNelen** [comment]
Yeah I would definitely try to implement this. You're totally correct that current implementation can appear as cheap.

This plugin has some nice functionality in terms of customizing when to show the popup, e.g. after X times launching the app, after X days, also options to remind users after X launches or days.
https://pub.dev/packages/rate_my_app#-example-tab-

**Comment by TNelen** [comment]
#196 can be closed since it is related.

**Comment by Nuytemans-Dieter** [comment]
> Yeah I would definitely try to implement this. You're totally correct that current implementation can appear as cheap.
> 
> This plugin has some nice functionality in terms of customizing when to show the popup, e.g. after X times launching the app, after X days, also options to remind users after X launches or days.
> https://pub.dev/packages/rate_my_app#-example-tab-

That will come in handy, thanks. Will take a better look soon.

**Comment by TNelen** [comment]
rate this app button is removed; So no need for this.
