### ISSUE TITLE
implement auto notifications in firebase for inactive users

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#246]
buiild further on #148

Firebase has the functionality to send messages to players 
- when they have not used the app for X amount of days.
- when X days have passed since they first opened the app. 

@Nuytemans-Dieter . Which filter do you prefer? and what would be the ideal amount of days you think?

My take:
- First filter
- 14 days

**Comment by Nuytemans-Dieter** [comment]
I agree on using the first filter, this reminds inactive users that BlackBox exists.
The ideal amount of days is harder to decide, a multiple of 7 days seems like a good idea to me. One week is probably too quick and spammy so 14 days should indeed be a good starting point.
