### ISSUE TITLE
improve animations between screens

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#253]

**Comment by Nuytemans-Dieter** [comment]
Used code of a slide transition from [Medium](https://medium.com/flutter-community/everything-you-need-to-know-about-flutter-page-route-transition-9ef5c1b32823). See d55b4cc430f6e54fbc49ba78e411b40e97570729.
All non ingame screens (settings/help for example) do not have this animation as they will get a seperate animation later.

**Comment by Nuytemans-Dieter** [comment]
Implemented scaling transitions for other screens in d55b4cc430f6e54fbc49ba78e411b40e97570729
